askdjango/urls.py
from django.shortcuts import redirect

from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

from . import views

def root(request):
    return redirect('blog:post_list')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^dojo/', include('dojo.urls', namespace='dojo')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^shop/', include('shop.urls', namespace='shop')),


    #url(r'^$', root, name='root')
    url(r'^$', lambda r: redirect('blog:post_list'), name='root')
    #url(r'^$', RedirectView.as_view(pattern_name='blog:post_list')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

blog/urls.py
#blog/urls.py
from django.conf.urls import url
from . import views, views_cbv

urlpatterns = [
    #url(r'^$', views_cbv.post_list, name = 'post_list'),
    url(r'^$', views.post_list, name = 'post_list'),
    #url(r'^(?P<pk>\d+)/$', views_cbv.post_detail, name='post_detail'),
    url(r'^(?P<pk>\d+)/$', views.post_detail, name='post_detail'),

    url(r'^new/$', views.post_new, name='post_new'),
    url(r'^(?P<id>\d+)/edit/$', views.post_edit, name='post_edit'),

    url(r'^cbv/new/$', views_cbv.post_new),
    url(r'^cbv/(?P<pk>\d+)/edit/$', views_cbv.post_edit),
    url(r'^cbv/(?P<pk>\d+)/delete/$', views_cbv.post_delete),



]

blog/models.py
import re
from django.db import models
from django.forms import ValidationError
from django.conf import settings
from django.core.urlresolvers import reverse

from imagekit.models import ImageSpecField
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail

# Create your models here.

class Post(models.Model):
    STATUS_CHOICE = (
        ('d', 'Draft'),
        ('p', 'Published'),
        ('w', 'Withdrawn'),
    )


    def lnglat_validator(value):
        if not re.match(r'^([+-]?\d+\.?\d*),([+-]?\d+\.?\d*)$', value):
            raise ValidationError('Invalid LngLat Type')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='blog_post')
    #author = models.CharField(max_length=20)
    title = models.CharField(max_length=100, verbose_name='제목',
                             help_text='포스팅 제목을 입력하세요 최대 100자')
    content = models.TextField(verbose_name='내용')


    '''원본을 유지 한 상태로.'''
    photo = models.ImageField(blank=True, upload_to='blog/post/%Y/%m/%d')
    photo_thumbnail = ImageSpecField(source='photo',
                                     processors=[Thumbnail(300, 300)],
                                     format='JPEG',
                                     options={'quality': 60})
    '''
    원본 없이 섬네일만 저장 할 때
    photo = ProcessedImageField(blank=True, upload_to='blog/post/%Y/%m/%d',
                                processors=[Thumbnail(300, 300)],
                                format='JPEG',
                                options={'quality': 60})
    '''

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tag = models.CharField(max_length=100, blank=True)
    lnglat = models.CharField(max_length=50, blank=True,
                              validators=[lnglat_validator],
                              help_text='경도/위도 포맷으로 입력')
    status = models.CharField(max_length=1, choices=STATUS_CHOICE)
    tag_set =models.ManyToManyField('Tag', blank=True)
    #Tag 모델이 뒤에 정의되어 있기 때문에 문자열로 넣었음.)


    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.id])

class Comment(models.Model):
    post = models.ForeignKey(Post)
    author = models.CharField(max_length=20)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True )

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from .models import Post
from askdjango.widgets.naver_map_point_widget import NaverMapPointWidget

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        widgets = {
            'lnglat': NaverMapPointWidget(attrs={'width': 600,
                                                'height': 300}),
        }

blog/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from .models import Post
from .forms import PostForm

# Create your views here.

def post_list(request):
    print(request.user.is_authenticated)

    qs = Post.objects.all()

    q = request.GET.get('q', '')
    if q:
        qs = qs.filter(title__icontains=q)

    response = render(request, 'blog/post_list.html', {
        'post_list': qs,
        'q': q,
    })
    # render의 반환값은 HttpResponse 인스턴스임.
    # render를 통해서, 좀 더 쉽게 탬플릿을 통한 랜더링
    return response

def post_detail(request, id):
    # try:
    #     post = Post.objects.get(id=id)
    # except Post.DoesNotExist:
    #     raise Http404

    post = get_object_or_404(Post, id=id)

    return render(request, 'blog/post_detail.html', {
        'post': post
    })

def post_new(request):
    if request.method=='POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid:
            post = form.save()
            messages.success(request, '새 포스팅을 저장했습니다.')
            return redirect(post) # post.get_absolute_url()로 이동
    else:
        form = PostForm()
    return render(request, 'blog/post_form.html', {
        'form' : form,
    })

def post_edit(request, id):
    post = get_object_or_404(Post, id=id)

    if request.method=='POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid:
            post = form.save()
            messages.success(request, '수정 되었습니다.')
            return redirect(post) # post.get_absolute_url()로 이동
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_form.html', {
        'form': form,
    })

blog/templates/blog/layout.html
{% extends "layout.html" %}

{% block title %}AskDjango's blog man {% endblock %}

blog/templates/blog/post_confirm_delete.html
<h1>{{post}} 삭제확인</h1>

정말 삭제하시겠습니까?

<form action="" method="post">
    {% csrf_token %}
    <a href="{{ post.get_absolute_url }}">취소</a>
    <input type="submit" value="예 삭제하겠습니다.">
</form>

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}
{% load imagekit %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            {% block title %}

            {{post.title}}
            {% endblock %}

            <h2>{{post.title}}</h2>

            <!--<img src="/media/{{post.photo}}" style="max-width: 100%" />-->
            {% if post.photo %}
                <img src="{{ post.photo_thumbnail.url }}" style="max-width: 100%" />

                {% comment %}
                    thumbnail 탬플릿 태그를 썼을 때 뒤에 as 로 별칭을 주면 따로 출력해주지 않는다.
                    고로 뒤에 img 태그에 커스텀하게 구성가능
                {% endcomment %}
                {% thumbnail "200x200" post.photo as thumb %}
                <img src="{{thumb.url}}" width="{{ thumb.width}}", height="{{thumb.height}}" />


                {% comment %}
                    thumbnail 탬플릿 태그에 찍찍 그으면 style, onclick, class 등의 속성을 쓸 수 있다.
                    {% thumbnail "200x200" post.photo -- style="" onclick="" class="" %}
                {% endcomment %}


            {% endif %}
            <p>{{post.content|linebreaks}}</p>
            <hr/>

            <h3>Comments</h3>
            <ul>
                {% for comment in post.comment_set.all %}
                <li>
                    {{comment.message}}
                    <small>by {{comment.author}}</small>
                    <small>at {{comment.updated_at}}</small>
                </li>
                {% endfor %}
            </ul>

            <hr/>
            <a href="{% url "blog:post_list" %}" class="btn btn-primary">목록</a>
            <a href="{% url "blog:post_edit" post.id %}" class="btn btn-default">수정</a>
        </div>
    </div>
</div>
{% endblock content %}
</body>
</html>

blog/templates/blog/post_form.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table}}
    </table>
    <input type="submit" value="제출">
</form>

blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}

<div class="container">
    <div class="jumbotron">
        <h1>Django Template <sup>by AskDjango</sup></h1>
        <p>여러분의 파이썬/장고 페이스메이커가 되겠습니다.</p>
        <p>
            <a class="btn btn-lg btn-primary" href="http://facebook.com/groups/askdjango">
                AskDjango 페이스북 그룹 &raquo;
            </a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <a href="{% url "blog:post_new" %}" class="btn btn-primary pull-right">new Post</a>

        <p>
        <form action="" method="get">
            <input type="text" name="q" value="{{q}}"/>
            <input type="submit" value="검색" class="btn btn-primary">
        </form>
        </p>
        <table class="table table-hover table-bordered">
            <thead>
            <tr>
                <th>img</th>
                <th>id</th>
                <th>title</th>
                <th>author</th>
                <th>updated_at</th>
            </tr>
            </thead>
            <tbody>
            {% for post in post_list %}
            <tr>
                {% if post.photo %}
                <td class="col-sm-1"><img src="{{ post.photo_thumbnail.url }}" style="max-width: 100%"/></td>
                {% else %}
                <td class="col-sm-1"><img src="/media/flower.jpg" style="max-width: 100%"/></td>
                {% endif %}
                <td>{{ post.id }}</td>
                <!--<a href="/blog/{{post.id}}">-->
                <td><a href="{% url "blog:post_detail" post.id %}">
                    {{ post.title }}
                    </a>
                </td>
                <td>
                    <small>by {{post.author}}</small>
                </td>
                <td>
                    <small>at {{post.updated_at}}</small>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>


{% endblock %}